### ISSUE TITLE
做了端口转发后，读取Swagger-json的路径是绝对路径导致无法正常访问

### ISSUE THREAD

**Issue by pengyouak** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#13]
/v3/api-docs/swagger-config

**Comment by luoyunchong** [comment]
你用的什么转发。我这里用nginx配置个转发，也不会出现无法访问的问题。

**Comment by pengyouak** [comment]
自己写的一个Express中间件。

**Comment by pengyouak** [comment]
> 你用的什么转发。我这里用nginx配置个转发，也不会出现无法访问的问题。

自己写的Express中间件，这个接口可以正常转发，但是到这个UI上的时候会有问题，找不到swagger-json。

**Comment by luoyunchong** [comment]
那问题可能出现在这段。。。但我这边无法重现。。
```
          if (httpMethod == "GET" && Regex.IsMatch(path, $"^/v3/api-docs/swagger-config$"))
            {
                await RespondWithConfig(httpContext.Response);
                return;
            }
```

**Comment by dongdaluan** [comment]
很好重现的，只要把项目部署到IIS的虚拟目录下而不是根目录就会出错。
解决方法更改app.d4cb69c0.js文件，搜索/v3/api-docs/swagger-config， 改为../v3/api-docs/swagger-config。如下：
this.url=e.url||"../v3/api-docs/swagger-config",this.configUrl=e.configUrl||"../v3/api-docs/swagger-config"
