### ISSUE TITLE
API点击后跳转显示的都是相同内容

### ISSUE THREAD

**Issue by MoondanceZ** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#2]
我弄了个测试仓库, 你可以试一下
https://github.com/MoondanceZ/Knife4jUiTest.git

**Comment by luoyunchong** [comment]
先在AddSwaggerGen中这样改一下。。主要原因还是operationId存在重复的值。
```
                options.CustomOperationIds(apiDesc =>
                {
                    var controllerAction = apiDesc.ActionDescriptor as ControllerActionDescriptor;
                    return  controllerAction.ControllerName+"-"+controllerAction.ActionName;
                });
```

**Comment by MoondanceZ** [comment]
Ok了
还有个问题, 要是文件上传的接口, 没法跟之前的swagger那样可以直接上传..

**Comment by luoyunchong** [comment]
的确是的。现在这个用的Knife4j，swagger的v3版本，不知道v2如何。我只改了几个配置，就打包的，受限于上流功能。

后续看下，如何实现。java那边，他们不喜欢升级版本，基本都在v2版本。

**Comment by lvjunlei** [comment]
> 先在AddSwaggerGen中这样改一下。。主要原因还是operationId存在重复的值。
> 
> ```
>                 options.CustomOperationIds(apiDesc =>
>                 {
>                     var controllerAction = apiDesc.ActionDescriptor as ControllerActionDescriptor;
>                     return  controllerAction.ControllerName+"-"+controllerAction.ActionName;
>                 });
> ```

这样CustomOperationId还是与问题，比如一个分组里面有两个GET方法，他们的CustomOperationId就会重复，我直接使用了
o.CustomOperationIds(apiDesc =>
                {
                    var controllerAction = apiDesc.ActionDescriptor as ControllerActionDescriptor;
                    return $"ID-{controllerAction.GetHashCode()}";
                });
就没问题了

**Comment by luoyunchong** [comment]
@lvjunlei  知道原因就好，控制器方法重载，我还没遇到过，控制器方法重截，之前方法名一样，参数不一样，会遇到请求 时，无法根据参数确定是哪个方法。所以不会写一样的方法。
