### ISSUE TITLE
使用0.0.8的版本依然存在响应结果是下载文件

### ISSUE THREAD

**Issue by WildShooter** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#21]
我使用最新的IGeekFan.AspNetCore.Knife4JUI(0.0.8)，运行起来后，返回值依然是下载文件呢？我看你关闭的issue中说升级到0.0.2版本就已经解决了这个问题呢？还有就是咱们这个包还在一直更新吗？看最新版本还是2020年10月23日发布的

**Comment by luoyunchong** [comment]
试试在方法上加上特性标签。或升级最新版本。
```
     [Produces("application/octet-stream", Type = typeof(FileResult))]
```
