### ISSUE TITLE
我的返回实体的结构和描述没有显示出来，是需要配置什么吗？

### ISSUE THREAD

**Issue by xiaolei000129** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#22]

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/130347438-cd1be598-103e-4cda-b7ac-ec72f8df7749.png)

**Comment by xiaolei000129** [comment]
我已经生成了Model的xml了，但是还是没有显示出来

**Comment by luoyunchong** [comment]
web层的bin目录有没有这个xml

**Comment by xiaolei000129** [comment]
可以确定bin中有

**Comment by xiaolei000129** [comment]
![image](https://user-images.githubusercontent.com/44334120/130348022-20febe06-dd90-45f3-bb07-e7f3f0f7ad8f.png)
![image](https://user-images.githubusercontent.com/44334120/130348027-ba7073d6-df6a-487b-b22c-cf16024b12ef.png)

**Comment by xiaolei000129** [comment]
我是.net 5的环境

**Comment by luoyunchong** [comment]
返回 类型是什么。

**Comment by xiaolei000129** [comment]
![image](https://user-images.githubusercontent.com/44334120/130348212-192d7481-f5e2-43f7-81a4-b795ac496eee.png)

**Comment by luoyunchong** [comment]
直接return result

**Comment by xiaolei000129** [comment]
嗯嗯确实可以这样

**Comment by xiaolei000129** [comment]
但是我使用原生的时候可以兼容，希望作者也可以安排一下呗

**Comment by luoyunchong** [comment]
原生没看到有支持

**Comment by xiaolei000129** [comment]
那可能是我的问题，我已经纠正了谢谢啦

**Comment by dianejason** [comment]
我用.net5也遇到这个问题了，大佬分享一下怎么处理参数描述和model描述 都没出来

**Comment by luoyunchong** [comment]
建 实体，不要返回 IActionResult类型。不然需要在特性标签上指定具体 的类型。如
```
        [HttpPost]
        [ProducesResponseType(typeof(int), 201)]
        [ProducesResponseType(typeof(IDictionary<string, string>), 400)]
        public IActionResult CreateOrder([FromBody, Required]Order order)
        {
            return new CreatedResult("/orders/1", 1);
        }
```
