### ISSUE TITLE
RoutePrefix 添加的情况下，swagger-resources 路径无效修复

### ISSUE THREAD

**Issue by xiaozhi8882001** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#26]
有时候，通过Nginx分路径转发不同API情况下，有必须用到 RoutePrefix ，但 swagger-resources 加前缀后访问不到，404报错。
查看源码得知：Knife4jUIMiddleware.cs 文件第69行，if (httpMethod == "GET" && Regex.IsMatch(path, $"^/swagger-resources$")) 改为 if (httpMethod == "GET" && Regex.IsMatch(path, $"/swagger-resources$"))，即可。这样的话，加了前缀的 swagger-resources 也可被请求到。
优化一下，方便其它人。
就这个小地方，我花了几个小时，尝试不行，不得已才查看源码找到的。
谢谢楼主的无私开源贡献！！！

**Comment by luoyunchong** [comment]
参考 https://github.com/luoyunchong/lin-cms-dotnetcore/blob/master/src/LinCms.Web/Startup/SwaggerExtensions.cs#L149

![image](https://user-images.githubusercontent.com/18613266/139617768-89fc0a64-c42c-4a95-aea8-a63a6ced86d6.png)

**Comment by luoyunchong** [comment]
c.AddServer(new OpenApiServer()
                {
                    Url = "http://localhost:81/admin/",
                    Description = "vvv"
                });
