### ISSUE TITLE
作者必看！0.0.11v 关于显示接口名与授权问题！

### ISSUE THREAD

**Issue by ccnetcore** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#28]
您好，作者，我和大部分其他人早已经发现，默认的丝袜哥ui界面不够现代化，且没法保存上一次的编辑记录，关于调试接口与授权每一次都没重新输入，**确实需要一个更完美的ui了**！！！
我们是从早期版本开始使用的，操作起来确实方便了不少，对于目前现状，我认为有很大的意义！
不过目前存在一下两点不足：（我们这块反应的人也挺多的）
## 关于鉴权：
![image](https://user-images.githubusercontent.com/68722157/141228388-5c499e29-973b-4c91-8418-098d9fd57a55.png)
好像是无效的，我们只能通过全局配置进行添加
## 关于显示：
在0.0.11v添加了控制器显示，很舒服，但是：
当有注释存在的情况下，无法让菜单显示的是接口名
![image](https://user-images.githubusercontent.com/68722157/141228536-0c329e2f-eb0d-491f-a900-1e04f7b87bf5.png)
如果没有注释或者为空注释：
![image](https://user-images.githubusercontent.com/68722157/141228582-cf613db7-8d2a-4ae0-9875-4dba5fc97ff6.png)
有的时候，应该让接口名显示，后跟注释

最后，感谢作者让我们的API文档接口与java齐平~~~

**Comment by luoyunchong** [comment]
本来就是knif4j直接npm run build的。只是他的配置项不能直接在.net core这边做一些配置。
