### ISSUE TITLE
是否支持OAuth 2.0授权

### ISSUE THREAD

**Issue by lonverce** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#3]
我的API需要向IdentityServer验证获取AccessToken后才能调用, 这一点在之前使用原生SwaggerUI时就已经实现, 现在迁移到Knife4jUI, 却发现界面上不再支持认证流程, 请问我是否该弃坑?

**Comment by luoyunchong** [comment]
@lonverce   会安排的。。正好周末了，有空了，看下如何实现。

**Comment by RwLin69** [comment]
请问支持OAuth 2.0授权这块功能有实现了吗 @luoyunchong

**Comment by luoyunchong** [comment]
@RwLin69 
这个功能是上游UI的功能，我也在尝试处理， [https://gitee.com/igeekfan/knife4j/tree/igeekfan-dev/knife4j-vue-v3](https://gitee.com/igeekfan/knife4j/tree/igeekfan-dev/knife4j-vue-v3)，不过这个比较复杂，有做一部分了。

**Comment by luoyunchong** [comment]
https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/issues/37
