### ISSUE TITLE
控制器和实际展示名称不一致

### ISSUE THREAD

**Issue by xiaolei000129** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#38]
![image](https://user-images.githubusercontent.com/44334120/162657816-405970ae-e112-42b5-b687-275531100cfb.png)

![image](https://user-images.githubusercontent.com/44334120/162657861-28a40b8e-b78f-4558-a502-7bc0c62274c6.png)

Json数据是正常的

**Comment by luoyunchong** [comment]
```
   services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("v1",new OpenApiInfo{Title = "API V1",Version = "v1"});
        c.AddServer(new OpenApiServer()
        {
            Url = "",
            Description = "vvv"
        });
        c.CustomOperationIds(apiDesc =>
        {
            var controllerAction = apiDesc.ActionDescriptor as ControllerActionDescriptor;
            return  controllerAction.ControllerName+"-"+controllerAction.ActionName;
        });
    });
```

要配置CustomOperationIds，因为他根据 opertaionId查的数据的。

https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/issues/2
