### ISSUE TITLE
多api集成时调用地址与swagger定义的地址无关，都是本地地址

### ISSUE THREAD

**Issue by yanusosu** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#4]
我在UI中集成了两个api地址，第一个是/，第二个是/v2。但是调用v2的api时请求的还是/。
并且添加服务地址的在ui中也没体现
 c.AddServer(new OpenApiServer()
        {
            Url = "url1",
            Description = "vvv"
        });

**Comment by luoyunchong** [comment]
问题存在，会安排处理。

**Comment by luoyunchong** [comment]
这个问题解决了。使用最新版本试试。

### 示例
https://api.igeekfan.cn/swagger/index.html

https://github.com/luoyunchong/lin-cms-dotnetcore/blob/master/src/LinCms.Web/Startup/SwaggerExtensions.cs

**Comment by yanusosu** [comment]
更新最新版本问题已解决，感谢
