### ISSUE TITLE
返回404/401 显示文件

### ISSUE THREAD

**Issue by FatuityCookie** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#44]
示例项目：AspNetCore6Api 
返回内容：显示文件

![image](https://user-images.githubusercontent.com/46119806/186084402-cbe66517-1173-4b7a-b86c-8fb7fdde5b57.png)
![image](https://user-images.githubusercontent.com/46119806/186084899-d8030be0-5bcd-4eba-a9eb-ef182052273c.png)

**Comment by luoyunchong** [comment]
前端项目：https://gitee.com/xiaoym/knife4j/tree/master

这边改不了

**Comment by luoyunchong** [comment]
目前版本目前存在很多问题，这些在前端issues都有体现，2.0版本对openapi 3.0 支持有限

需要看后续 knife4j 的v4.0.0版本如何
