### ISSUE TITLE
参数是枚举类型的时候是有问题的

### ISSUE THREAD

**Issue by 786744873** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#5]
![image](https://user-images.githubusercontent.com/24601648/90849750-96a7ae00-e3a2-11ea-8a21-c4fb66414d79.png)

**Comment by luoyunchong** [comment]
这个问题解决了。使用最新版本试试。

### 示例
https://api.igeekfan.cn/swagger/index.html

https://github.com/luoyunchong/lin-cms-dotnetcore/blob/master/src/LinCms.Web/Startup/SwaggerExtensions.cs
