### ISSUE TITLE
支持 FastEndpoints 框架么？

### ISSUE THREAD

**Issue by zfchai** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#51]
当前 **FastEndpoints.Swagger** 的 nuget 包是基于 **NSwag.AspNetCore** 的，目前 FastEndpoints 框架的提供者不考虑支持 **Swashbuckle.AspNetCore.Swagger** 这个包集成 FastEndpoints.Swagger 的支持，请问 **IGeekFan.AspNetCore.Knife4jUI** 可以提供对  FastEndpoints 框架的支持么？

- FastEndpoints：https://fast-endpoints.com/

**Comment by luoyunchong** [comment]
本项目没有任何 Swagger的相关依赖

用户自行引用相关的包

https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI#nswagaspnetcore

![image](https://user-images.githubusercontent.com/18613266/234232087-9faba11c-45bb-49c5-a25f-d096e4ed04a2.png)

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/234234092-fe7c1c38-6b56-4b09-a679-b8c4afd6a3db.png)

你可以试试有问题再说，本来就支持NSwag.AspNetCore

**Comment by luoyunchong** [comment]
[Solution1.zip](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/files/11321088/Solution1.zip)

没区别，他的保持不变，然后中间件用这边的。

**Comment by zfchai** [comment]
没法使用，可以给一个  IGeekFan.AspNetCore.Knife4jUI 在 FastEndpoints 框架中使用的 demo 参考么，我本地尝试运行报错了。

**Comment by zfchai** [comment]
Solution1.zip 这个 demo 已经下载运行了，运行页面如下：

![image](https://user-images.githubusercontent.com/82487746/234252313-4216460b-f3a0-479a-b5ea-69a6121e34b8.png)

怎么实现 API 分组显示的效果呢？例如有以下两个分组：

- A 分组：
1、/api/user/create
2、/api/user/get

- B 分组：
1、/api/org/create
2、/api/org/get

预期效果：选择左上角的下拉选择框，可以实现显示对应分组的 api 信息。

目前 IGeekFan.AspNetCore.Knife4jUI 可以做到这样的效果么？

**Comment by zfchai** [comment]
这个需求目的是方便管理 API（按功能模块分组），并非版本管控的概念，只需要 API 能分组管理即可。
