### ISSUE TITLE
0.14版本，请求参数如果有枚举类型，会导致整个接口文档都不显示，0.13、0.12正常

### ISSUE THREAD

**Issue by rain7788** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#55]
0.14版本，请求参数如果有枚举类型，会导致整个接口文档都不显示，0.13、0.12正常

**Comment by luoyunchong** [comment]
升级 [0.0.16](https://www.nuget.org/packages/IGeekFan.AspNetCore.Knife4jUI/0.0.16)
