### ISSUE TITLE
0.14版本 Controller的注释不会显示 0.13正常

### ISSUE THREAD

**Issue by NENCAO** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#56]
![image](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/13777693/754c1b26-f076-4472-84bd-c125d72c4cd7)
![image](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/13777693/1a9b2b49-6694-4e1a-97ad-14cbdad298e7)
![image](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/13777693/d2a45f90-7271-40d4-95f8-aa8461295596)

**Comment by LemonNoCry** [comment]
我也遇到同样问题

**Comment by luoyunchong** [comment]
升级 [0.0.16](https://www.nuget.org/packages/IGeekFan.AspNetCore.Knife4jUI/0.0.16)
