### ISSUE TITLE
自定义类型显示为string，而且也没有加载出来。

### ISSUE THREAD

**Issue by HisKingdom** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#57]
<img width="572" alt="2" src="https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/10276556/e119b236-f33c-4fa3-a9a7-71539fa87a15">
<img width="813" alt="1" src="https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/10276556/b295352f-c802-48ad-b971-bd442ff3b6a0">

**Comment by HisKingdom** [comment]
请求参数是正常显示的，我这个是响应参数不显示。

**Comment by luoyunchong** [comment]
https://gitee.com/xiaoym/knife4j

**Comment by HisKingdom** [comment]
已经解决了，是我自己使用的问题，我是参考https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/issues/11 使用nswag(swagger)和AddOpenApiDocument造成的，后续按照你的配置就好了。
