### ISSUE TITLE
属性不为 "public set"的时候， 接口文档上的响应示例的Json里面不会显示该字段。

### ISSUE THREAD

**Issue by Naughtyhusky** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#58]
![image](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/50131126/7db486a1-2e13-4163-9a9e-ddc19716b368)

![image](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/50131126/6fe75277-3ea2-44d4-90e3-20b156a5c0f4)

下方的响应格式里面，没有IsSuccess 字段。

实际请求时候的响应里面是有的：

![67b6aee177db823e66fbe06677131ad](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/50131126/f8e3e36a-328b-4eb6-960e-b293a2bb9798)

经过测试，将 Code 等字段改为  protected set 的时候，会有相同的问题。

nuget 版本 从 0.0.13 - 最新的0.0.16 均存在此问题。

**Comment by luoyunchong** [comment]
![bd68c564ac6fdfe6740b5a4b5a512a5](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/assets/18613266/3c0222aa-59bb-451c-b69d-eace23cab437)

**Comment by luoyunchong** [comment]
https://gitee.com/xiaoym/knife4j

**Comment by Naughtyhusky** [comment]
但是这样一刀切，不觉得很奇怪嘛，这个是响应参数的示例，是后端返回的，不管它是不是readonly，都应该展示出来。

**Comment by luoyunchong** [comment]
这是这个UI的问题，你可以去他的gitee上问问
