### ISSUE TITLE
请求参数是form-data时无法显示请求示例，调试也没办法添加添加请求参数

### ISSUE THREAD

**Issue by lvyi21** [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#9]
接口请求参数标注为[FromForm]时，界面中的文档请求示例显示不出来，调试中的请求参数也没显示，导致无法传参数进行调试

**Comment by luoyunchong** [comment]
加个下面这个特性标签试试呢。
```
        [Consumes("application/x-www-form-urlencoded")]
```

**Comment by lvyi21** [comment]
不起作用



在 2020-10-14 21:28:26，"IGeekFan" <notifications@github.com> 写道：

加个下面这个特性标签试试呢。

        [Consumes("application/x-www-form-urlencoded")]

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/146404526-9a3ee215-b68a-42e1-ba21-de7b60a467e2.png)

**Comment by PiZhai** [comment]
就是没用
